name: nf-core-smartseq2-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - bioconda::star=2.7.1a
  - bioconda::rsem=1.3.3
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.8
  - bioconda::subread=1.6.4
